name: OpDemand
url: http://opdemand.com/
tagline: Open source PaaS powered by Docker and Heroku
markdown: redcarpet
timezone: America/Denver
permalink: /:title
excerpt_separator: "<!--more-->"
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.ruby-version']
